export interface Tool {
  title: string;
  description: string;
  icon: string;
  category: string;
  id: string; // Add explicit ID matching folder name
}

export const tools: Tool[] = [
  {
    title: 'Merge PDF',
    id: 'merge-pdf',
    description: 'Combine multiple PDFs into one document.',
    icon: 'merge_type',
    category: 'basic',
  },
  {
    title: 'Split PDF',
    id: 'split-pdf',
    description: 'Extract specific pages or ranges from a PDF.',
    icon: 'call_split',
    category: 'basic',
  },
  {
    title: 'Compress PDF',
    id: 'compress-pdf',
    description: 'Reduce the file size of your PDF.',
    icon: 'compress',
    category: 'basic',
  },
  {
    title: 'Rotate PDF',
    id: 'rotate-pdf',
    description: 'Rotate the pages of your PDF.',
    icon: 'rotate_90_degrees_cw',
    category: 'basic',
  },
  {
    title: 'Delete Pages',
    id: 'delete-pdf-pages', // Fixed ID to match folder name 'delete-pdf-pages'
    description: 'Remove specific pages from a PDF.',
    icon: 'delete',
    category: 'basic',
  },
  {
    title: 'Reorder Pages',
    id: 'reorder-pages',
    description: 'Change the order of pages in a PDF.',
    icon: 'reorder',
    category: 'basic',
  },
  {
    title: 'PDF to JPG',
    id: 'pdf-to-jpg',
    description: 'Convert PDF pages to JPG images.',
    icon: 'image',
    category: 'convert',
  },
  {
    title: 'JPG to PDF',
    id: 'jpg-to-pdf',
    description: 'Convert JPG images to a PDF.',
    icon: 'picture_as_pdf',
    category: 'convert',
  },
  {
    title: 'PDF to Word',
    id: 'pdf-to-word',
    description: 'Convert a PDF to an editable Word document.',
    icon: 'description',
    category: 'convert',
  },
  {
    title: 'PDF to Excel',
    id: 'pdf-to-excel',
    description: 'Extract tables from a PDF into an Excel spreadsheet.',
    icon: 'table_chart',
    category: 'convert',
  },
  {
    title: 'PDF to PPT',
    id: 'pdf-to-ppt',
    description: 'Convert a PDF to a PowerPoint presentation.',
    icon: 'slideshow',
    category: 'convert',
  },
  {
    title: 'Word to PDF',
    id: 'word-to-pdf',
    description: 'Convert a Word document to a PDF.',
    icon: 'picture_as_pdf',
    category: 'convert',
  },
  {
    title: 'Excel to PDF',
    id: 'excel-to-pdf',
    description: 'Convert an Excel spreadsheet to a PDF.',
    icon: 'picture_as_pdf',
    category: 'convert',
  },
  {
    title: 'PPT to PDF',
    id: 'ppt-to-pdf',
    description: 'Convert a PowerPoint presentation to a PDF.',
    icon: 'picture_as_pdf',
    category: 'convert',
  },
  {
    title: 'PDF to Text',
    id: 'pdf-to-text',
    description: 'Extract text from a PDF.',
    icon: 'text_fields',
    category: 'convert',
  },
  {
    title: 'HTML to PDF',
    id: 'html-to-pdf',
    description: 'Convert a webpage to a PDF.',
    icon: 'web',
    category: 'convert',
  },
  {
    title: 'Add Watermark',
    id: 'add-watermark',
    description: 'Add a text or image watermark to your PDF.',
    icon: 'branding_watermark',
    category: 'edit',
  },
  {
    title: 'Add Page Numbers',
    id: 'add-page-numbers',
    description: 'Insert page numbers into your PDF.',
    icon: 'format_list_numbered',
    category: 'edit',
  },
  {
    title: 'Crop PDF',
    id: 'crop-pdf',
    description: 'Crop the pages of your PDF.',
    icon: 'crop',
    category: 'edit',
  },
  {
    title: 'Resize Pages',
    id: 'resize-pages',
    description: 'Change the size of the pages in your PDF.',
    icon: 'aspect_ratio',
    category: 'edit',
  },
  {
    title: 'Flatten PDF',
    id: 'flatten-pdf',
    description: 'Flatten the layers of your PDF.',
    icon: 'layers',
    category: 'edit',
  },
  {
    title: 'Protect PDF',
    id: 'protect-pdf',
    description: 'Add a password to your PDF.',
    icon: 'lock',
    category: 'security',
  },
  {
    title: 'Unlock PDF',
    id: 'unlock-pdf',
    description: 'Remove a password from your PDF.',
    icon: 'lock_open',
    category: 'security',
  },
  {
    title: 'Restrict Printing/Copying',
    id: 'restrict-printing-copying',
    description: 'Set permissions on your PDF.',
    icon: 'block',
    category: 'security',
  },
  {
    title: 'View Metadata',
    id: 'view-metadata',
    description: 'View the metadata of your PDF.',
    icon: 'info',
    category: 'security',
  },
  {
    title: 'Remove Metadata',
    id: 'remove-metadata',
    description: 'Remove the metadata from your PDF.',
    icon: 'info_outline',
    category: 'security',
  },
  {
    title: 'Repair Corrupted PDF',
    id: 'repair-corrupted-pdf',
    description: 'Attempt to repair a corrupted PDF.',
    icon: 'build',
    category: 'utility',
  },
  {
    title: 'Optimize PDF Size',
    id: 'optimize-pdf-size',
    description: 'Further reduce the size of your PDF.',
    icon: 'speed',
    category: 'utility',
  },
  {
    title: 'PDF Version Converter',
    id: 'pdf-version-converter',
    description: 'Change the PDF version of your document.',
    icon: 'system_update_alt',
    category: 'utility',
  },
  {
    title: 'PDF Analytics',
    id: 'pdf-analytics',
    description: 'Get information about your PDF.',
    icon: 'analytics',
    category: 'utility',
  },
  {
    title: 'PDF Table Extractor',
    id: 'pdf-table-extractor',
    description: 'Extract tables from your PDF to Excel or CSV.',
    icon: 'table_rows',
    category: 'advanced',
  },
  {
    title: 'Scan to PDF',
    id: 'scan-to-pdf',
    description: 'Convert a scanned document to a PDF.',
    icon: 'scanner',
    category: 'advanced',
  },
  {
    title: 'Screenshot to PDF',
    id: 'screenshot-to-pdf',
    description: 'Convert a screenshot to a PDF.',
    icon: 'screenshot',
    category: 'advanced',
  },
  {
    title: 'Image to PDF',
    id: 'image-to-pdf',
    description: 'Convert images (JPG, PNG) to PDF.',
    icon: 'image',
    category: 'convert',
  },
  {
    title: 'Batch Image to PDF',
    id: 'batch-image-to-pdf',
    description: 'Convert multiple images to a single PDF.',
    icon: 'burst_mode',
    category: 'advanced',
  },
  {
    title: 'Batch Processing',
    id: 'batch-processing',
    description: 'Process multiple files at once.',
    icon: 'dynamic_feed',
    category: 'workflow',
  },
  {
    title: 'Multi-step Workflow Presets',
    id: 'multi-step-workflow-presets',
    description: 'Create and save custom workflows.',
    icon: 'playlist_add_check',
    category: 'workflow',
  },
  {
    title: 'Chat with PDF',
    id: 'chat-with-pdf',
    description: 'Bate karo apne PDF ke saath using AI.',
    icon: 'chat',
    category: 'ai',
  },
  {
    title: 'PDF Summary',
    id: 'pdf-summary',
    description: 'Get a quick summary of your PDF content.',
    icon: 'summarize',
    category: 'ai',
  },
  {
    title: 'Compare PDFs',
    id: 'compare-pdfs',
    description: 'Compare two PDFs side by side.',
    icon: 'compare',
    category: 'advanced',
  },
  {
    title: 'Annotate PDF',
    id: 'annotate-pdf',
    description: 'Draw, highlight, and add comments to your PDF.',
    icon: 'edit_note',
    category: 'edit',
  },
  {
    title: 'Fill & Sign PDF',
    id: 'fill-and-sign',
    description: 'Fill forms and sign your PDF documents.',
    icon: 'draw',
    category: 'edit',
  },
  {
    title: 'PDF to Audio',
    id: 'pdf-to-audio',
    description: 'Listen to your PDF content.',
    icon: 'headphones',
    category: 'ai',
  },
  {
    title: 'Deskew PDF',
    id: 'deskew-pdf',
    description: 'Straighten scanned PDF pages.',
    icon: 'crop_rotate',
    category: 'advanced',
  },
  {
    title: 'Redact PDF',
    id: 'redact-pdf',
    description: 'Permanently remove sensitive information.',
    icon: 'visibility_off',
    category: 'security',
  },
  {
    title: 'PDF Translator',
    id: 'pdf-translator',
    description: 'Translate your PDF to another language.',
    icon: 'translate',
    category: 'ai',
  },
  {
    title: 'Share PDF with Expiry',
    id: 'share-pdf',
    description: 'Share your PDF with a temporary link.',
    icon: 'share',
    category: 'utility',
  },
  {
    title: 'Sign PDF',
    id: 'sign-pdf',
    description: 'Sign PDF documents online.',
    icon: 'draw',
    category: 'edit',
  },
];
